"""Add comment column to Recommend model

Revision ID: a2648b6526f8
Revises: db0dc4b2cf31
Create Date: 2024-09-28 04:47:43.135245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2648b6526f8'
down_revision = 'db0dc4b2cf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend', 'comment')
    # ### end Alembic commands ###
