"""Initial migration after reset

Revision ID: f768c0f376f7
Revises: 
Create Date: 2024-10-14 13:42:33.628125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f768c0f376f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('likes', 'recommendation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'condition_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'store_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('recommendations', 'store_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('recommendations', 'condition_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'recommendation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('business', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
